name: GitOps Deploykit
description: GitOps Style Manifest update with Kustomize
inputs:
    attempts:
        description: Number of git push retry attempts
        default: "3"
    backoff_method:
        description: the algorithm used to determine how long to wait before retry [exponential|random]
        default: random
    directory:
        description: The directory of an existing repository
        required: true
    image:
        description: The container image name to use in the kustomize command
        required: true
    manifest_deploy_token:
        description: The token used to read/write to the manifest repository
    manifest_email:
        description: The email set for git when commiting to the manifest repo
        default: github-actions[bot]@users.noreply.github.com
        required: true
    manifest_user:
        description: The user set for git when commiting to the manifest repo
        default: github-actions[bot]
        required: true
    message:
        description: override the default git commit message
        default: 'deploykit: push IMAGE to SERVICE in SDIR'
    repository:
        description: The directory of an existing repository
        required: true
    service:
        description: the destination service for the kustomize command
        required: true
    service_directory:
        description: The sub-directory (or environment) where the target kustomization.yaml file is located
    skip_push:
        description: Do the update but do not push commit
        default: "false"
runs:
    using: docker
    image: docker://ghcr.io/gatecheckdev/deploykit-action:v1.0.0-rc.1
    env:
        DK_ATTEMPTS: ${{ inputs.attempts }}
        DK_BACKOFF_METHOD: ${{ inputs.backoff_method }}
        DK_DIRECTORY: ${{ inputs.directory }}
        DK_IMAGE: ${{ inputs.image }}
        DK_MESSAGE: ${{ inputs.message }}
        DK_REPOSITORY: ${{ inputs.repository }}
        DK_SERVICE: ${{ inputs.service }}
        DK_SERVICE_DIRECTORY: ${{ inputs.service_directory }}
        DK_SKIP_PUSH: ${{ inputs.skip_push }}
