name: GitOps DeployKit
description: GitOps Style Manifest update with Kustomize
inputs:
  manifest-user:
    description: "The manifest user for the image update commit"
    default: "github-actions[bot]"
  manifest-email:
    description: "The manifest user email for the image update commit"
    default: "github-actions[bot]@users.noreply.github.com"
  attempts:
    description: "The number of times to try pushing the image update commit"
    default: "3"
  backoff-method:
    description: "the algorithm used to determine the wait duration between retry attempts"
    default: "random"
  image:
    description: "The container image name to use in the kustomize command"
  message:
    description: "A custom message to use for the image update commit"
  repository:
    description: "The target repository to clone using git"
  directory:
    description: "The directory of an existing target repository"
  service:
    description: "the destination service for the kustomize command"
  service-directory:
    description: "the sub-directory (or environment) where the target kustomization.yaml file is located"
runs:
  using: docker
  image: Dockerfile
  env:
    DK_MANIFEST_USER: ${{ inputs.manifest-user }}
    DK_MANIFEST_EMAIL: ${{ inputs.manifest-user-email }}
    DK_ATTEMPTS: ${{ inputs.attempts }}
    DK_BACKOFF_METHOD: ${{ inputs.backoff-method }}
    DK_IMAGE: ${{ inputs.image }}
    DK_MESSAGE: ${{ inputs.message }}
    DK_DIRECTORY: ${{ inputs.directory }}
    DK_SERVICE: ${{ inputs.service }}
    DK_SERVICE_DIRECTORY: ${{ inputs.service }}
