name: GitOps Deploykit
description: GitOps Style Manifest update with Kustomize
inputs:
    attempts:
        description: Number of git push retry attempts
        default: 3
    backoff_method:
        description: the algorithm used to determine how long to wait before retry [exponential|random]
        default: random
    directory:
        description: The directory of an existing repository
        default: ""
        required: true
    image:
        description: The container image name to use in the kustomize command
        default: ""
        required: true
    message:
        description: override the default git commit message
        default: 'deploykit: push IMAGE to SERVICE in SDIR'
    repository:
        description: The directory of an existing repository
        default: ""
        required: true
    service:
        description: the destination service for the kustomize command
        default: ""
        required: true
    service_directory:
        description: The sub-directory (or environment) where the target kustomization.yaml file is located
        default: ""
    skip_push:
        description: Do the update but do not push commit
        default: false
runs:
    using: docker
    image: Dockerfile
    env:
        attempts: ${{ inputs.attempts }}
        backoff_method: ${{ inputs.backoff_method }}
        directory: ${{ inputs.directory }}
        image: ${{ inputs.image }}
        message: ${{ inputs.message }}
        repository: ${{ inputs.repository }}
        service: ${{ inputs.service }}
        service_directory: ${{ inputs.service_directory }}
        skip_push: ${{ inputs.skip_push }}
